version: 0.2

env:
  variables:
    MASTER_PROJECT: .\NEsper.proj
    PACKAGE_DIRECTORY: .\packages
    VERSION: 8.6.0

phases:
  build:
    commands:
      - '& "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" /t:Distribution $env:MASTER_PROJECT'

artifacts:
  files:
    - .\build\NEsper-$env:VERSION
